site_name: chitra
site_description: Computer Vision Utility library
repo_url: https://github.com/aniketmaurya/chitra/
repo_name: aniketmaurya/chitra

theme:
  name: material
  logo: https://ik.imagekit.io/aniket/chitra/logo_ddSLdaURS.png
  favicon: https://ik.imagekit.io/aniket/chitra/favicon-32x32_zIf2gUdAN.png
  features:
    - search.suggest
    - search.highlight

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - git-revision-date-localized
  - search

extra:
  homepage: http://chitra.aniketmaurya.com
  nbs_image:
    base_url: https://raw.githubusercontent.com/aniketmaurya/chitra/master/docs/old_source/images

nav:
    - Introduction: 'index.md'
    - Examples:
        - Play with Images: 'examples/chitra-class/chitra-class.md'
        - Image Classification: 'examples/image-classification/image-classification.md'
    - License: 'license.md'