site_name: chitra
site_description: Rapid Computer Vision experiments
repo_url: https://github.com/aniketmaurya/chitra/
repo_name: aniketmaurya/chitra

theme:
  name: material
  logo: /assets/logo.png
  favicon: /assets/favicon/favicon.ico
  features:
    - search.suggest
    - search.highlight

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - git-revision-date-localized
  - search

extra:
  homepage: http://chitra.aniketmaurya.com
  nbs_image:
    base_url: https://raw.githubusercontent.com/aniketmaurya/chitra/master/docs/old_source/images

nav:
    - Introduction: 'index.md'
    - Examples:
        - Image Classification: 'image-classification-example/image-classification-example.md'
    - License: 'license.md'